INSERT INTO movies (
    title,
    category,
    synopsis,
    cast_members,
    director,
    producer,
    mpaa_rating,
    poster_url,
    trailer_url,
    status
) VALUES
(
    'Toy Story 5',
    'Animation',
    'Woody, Buzz, Jessie, and the rest of the toys face a new challenge as modern technology changes playtime.',
    'Tom Hanks, Tim Allen, Joan Cusack',
    'Andrew Stanton',
    'Pixar Animation Studios',
    'PG',
    'https://upload.wikimedia.org/wikipedia/en/thumb/0/08/Toy_Story_5_poster.jpg/250px-Toy_Story_5_poster.jpg',
    'https://www.youtube.com/embed/c51ND9Hdbw0?si=1nIUy4X6XgSRfdeQ',
    'CURRENTLY_PLAYING'
),
(
    'Supergirl',
    'Action',
    'Kara Zor-El begins a cosmic journey that tests her strength, identity, and place in the universe.',
    'Milly Alcock, Jason Momoa, Matthias Schoenaerts',
    'Craig Gillespie',
    'DC Studios',
    'PG-13',
    'https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Supergirl_%282026_film%29_poster.jpg/250px-Supergirl_%282026_film%29_poster.jpg',
    'https://www.youtube.com/embed/s1-pfiVMKAs?si=VeoQPuf7UEzrkfcM',
    'CURRENTLY_PLAYING'
),
(
    'The Death of Robin Hood',
    'Adventure',
    'A darker retelling of the Robin Hood legend, following an aging outlaw as he faces the consequences of his life and choices.',
    'Hugh Jackman, Jodie Comer, Bill Skarsgård',
    'Michael Sarnoski',
    'A24',
    'R',
    'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/The_Death_of_Robin_Hood_poster.jpeg/250px-The_Death_of_Robin_Hood_poster.jpeg',
    'https://www.youtube.com/embed/tlSDDuWxO_0?si=fwRTm8k3LSQsaq0X',
    'CURRENTLY_PLAYING'
),
(
    'Disclosure Day',
    'Science Fiction',
    'A global event changes how humanity understands its place in the universe.',
    'Emily Blunt, Colin Firth, Josh O Connor',
    'Steven Spielberg',
    'Universal Pictures',
    'PG-13',
    'https://upload.wikimedia.org/wikipedia/en/c/c3/Disclosure_Day_poster.jpg',
    'https://www.youtube.com/embed/SCYT8vb2siQ?si=BRyLB0EEPVo0iJ9I',
    'CURRENTLY_PLAYING'
),
(
    'Backrooms',
    'Horror',
    'A terrifying alternate space traps people inside endless rooms, strange corridors, and impossible environments.',
    'Chiwetel Ejiofor, Renate Reinsve, Mark Duplass',
    'Kane Parsons',
    'A24',
    'PG-13',
    'https://i0.wp.com/bloody-disgusting.com/wp-content/uploads/2026/02/HB2QAeeXIAAgDKc.jpg?resize=740%2C1097&ssl=1',
    'https://www.youtube.com/embed/0HjdiohVOik?si=htWB6kQ8DIf9Iuv2',
    'CURRENTLY_PLAYING'
),
(
    'Obsession',
    'Horror',
    'A wish made for love leads to dangerous consequences and a terrifying loss of control.',
    'Michael Johnston, Inde Navarrette, Andy Richter',
    'Curry Barker',
    'Blumhouse',
    'PG-13',
    'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Obsession_theatrical_poster.jpeg/250px-Obsession_theatrical_poster.jpeg',
    'https://www.youtube.com/embed/gMC8kkwbIQQ?si=wpZIoKXo0hJwToQw',
    'CURRENTLY_PLAYING'
),
(
    'Scary Movie',
    'Comedy',
    'A horror-comedy parody that returns with new jokes, familiar genre tropes, and modern slasher chaos.',
    'Anna Faris, Jon Abrahams, Marlon Wayans',
    'Keenen Ivory Wayans',
    'Paramount Pictures',
    'R',
    'https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Scary_Movie_%282026_film%29_poster.jpg/250px-Scary_Movie_%282026_film%29_poster.jpg',
    'https://www.youtube.com/embed/cGgWAHXuTKc?si=Ob-DhpJ3frSSQRTp',
    'CURRENTLY_PLAYING'
),
(
    'Masters of the Universe',
    'Fantasy',
    'He-Man returns to defend Eternia from powerful enemies in a new live-action adventure.',
    'Nicholas Galitzine, Camila Mendes, Idris Elba',
    'Travis Knight',
    'Amazon MGM Studios',
    'PG-13',
    'https://upload.wikimedia.org/wikipedia/en/thumb/0/09/Masters_of_the_Universe_2026_poster.jpeg/250px-Masters_of_the_Universe_2026_poster.jpeg',
    'https://www.youtube.com/embed/X21JsHLHnY8?si=14rw3u_KDcl9iL7Y',
    'CURRENTLY_PLAYING'
),
(
    'Minions & Monsters',
    'Animation',
    'The Minions create chaos in old Hollywood after their attempt to make a monster movie gets out of control.',
    'Pierre Coffin, Jesse Eisenberg, Zoey Deutch',
    'Pierre Coffin',
    'Illumination',
    'PG',
    'https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/Minions_%26_Monsters_poster.jpg/250px-Minions_%26_Monsters_poster.jpg',
    'https://www.youtube.com/embed/ZSdOwt-G49w?si=311rJnbaxursXRpO',
    'COMING_SOON'
),
(
    'Young Washington',
    'Historical Drama',
    'A historical drama focused on the early life and formation of George Washington.',
    'Cast TBA',
    'Director TBA',
    'Angel Studios',
    'PG-13',
    'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Young_Washington_poster.jpg/250px-Young_Washington_poster.jpg',
    'https://www.youtube.com/embed/LJek-kc384w?si=jr1y4U4HMYal1uDO',
    'COMING_SOON'
);